#!/usr/bin/python

from sys import argv, platform
from os import path

if '-no-incremental' in argv:
    remove_incremental = True
    argv.remove ('-no-incremental')
else:
    remove_incremental = False

if len(argv) < 2 or not argv[1].endswith ('.md'):
    raise ValueError ('expected markdown file with .md suffix')

html=''
markdown=''

with open ('_layouts/presentation.html') as fd:
    html = fd.read()

with open(argv[1]) as fd:
    npagebreak = 0
    for line in fd.readlines():
        if remove_incremental and line.strip() == '--':
            continue
        if npagebreak >= 2:
            markdown += line
        elif line.startswith ('title:'):
            title = line.split(maxsplit=1)[1].strip().strip('"')
        elif line.startswith ('---'):
            npagebreak +=1

out = argv[1][:-3]+'.html'

with open (out, 'w') as fd:
    fd.write (html.replace ('{{ page.title | strip_html }}', title).replace('{{ page.content }}', markdown))

filepath = path.abspath (out)
if platform == "cygwin":
  filepath = filepath[:2] + ':' + filepath[2:]

print ("ready to view at file:///" + filepath)

